//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamHoliday_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIEN()
        {
            this.LOCATION = new HashSet<LOCATION>();
        }
    
        public int idBien { get; set; }
        public string BIEN_Pays { get; set; }
        public string BIEN_ville { get; set; }
        public string BIEN_rue { get; set; }
        public string BIEN_numero { get; set; }
        public int idMembre { get; set; }
        public int BIEN_tarifParNuit { get; set; }
        public int BIEN_tarifNettoyage { get; set; }
        public Nullable<double> BIEN_noteMoyenne { get; set; }
        public string BIEN_libelle { get; set; }
        public string BIEN_photo { get; set; }
        public int BIEN_nbMaxPersonnes { get; set; }
    
        public virtual MEMBRE MEMBRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATION { get; set; }
        public virtual OPTIONS OPTIONS { get; set; }
        public virtual PIECE PIECE { get; set; }
    }
}
