//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamHoliday_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATION()
        {
            this.COMMENTAIRE = new HashSet<COMMENTAIRE>();
            this.NOTE = new HashSet<NOTE>();
        }
    
        public int idLocation { get; set; }
        public int idBien { get; set; }
        public int idMembre { get; set; }
        public System.DateTime LOC_dateEnregistrement { get; set; }
        public bool LOC_estCommente { get; set; }
        public bool LOC_estNote { get; set; }
        public System.DateTime LOC_dateArrivee { get; set; }
        public System.DateTime LOC_dateDepart { get; set; }
        public int LOC_nbNuits { get; set; }
    
        public virtual BIEN BIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTAIRE> COMMENTAIRE { get; set; }
        public virtual MEMBRE MEMBRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTE> NOTE { get; set; }
    }
}
