//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamHoliday_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        public double NOTE_note { get; set; }
        public int idMembre { get; set; }
        public int idBien { get; set; }
        public System.DateTime NOTE_date { get; set; }
        public int idLocation { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
    }
}
