//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamHoliday_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIONS
    {
        public int idBien { get; set; }
        public bool bbq { get; set; }
        public bool piscine { get; set; }
        public bool jacuzzi { get; set; }
        public bool sauna { get; set; }
        public bool tv { get; set; }
        public bool teledistribution { get; set; }
        public bool wifi { get; set; }
        public bool pingpong { get; set; }
        public bool tennis { get; set; }
        public bool transat { get; set; }
        public bool cuisine_equipee { get; set; }
        public bool machine_a_laver { get; set; }
        public bool jardin { get; set; }
        public bool parking { get; set; }
    
        public virtual BIEN BIEN { get; set; }
    }
}
