//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamHoliday_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIECE
    {
        public int idBien { get; set; }
        public int salleDeBain { get; set; }
        public int salon { get; set; }
        public int sallaAManger { get; set; }
        public int toilette { get; set; }
        public int cuisine { get; set; }
        public int chambre { get; set; }
        public int dressing { get; set; }
        public int veranda { get; set; }
    
        public virtual BIEN BIEN { get; set; }
    }
}
