//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamHoliday {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamHoliday.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string adresse {
            get {
                return ResourceManager.GetString("adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ajouter un bien.
        /// </summary>
        public static string ajouterUnBien {
            get {
                return ResourceManager.GetString("ajouterUnBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à barbecue.
        /// </summary>
        public static string bbq {
            get {
                return ResourceManager.GetString("bbq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour, bienvenue sur notre site..
        /// </summary>
        public static string Bienvenue01 {
            get {
                return ResourceManager.GetString("Bienvenue01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez un bien inhabité et aimeriez gagner de l&apos;argent en le louant? 
        ///ou vous voullez partir en couple ou entre amis sans casser votre tire-lire?
        ///DREAMHOLIDAY est fait pour VOUS!
        ///Nous permettons aux propriétaires de mettre leur bien en location en toute sécurité....
        /// </summary>
        public static string Bienvenue02 {
            get {
                return ResourceManager.GetString("Bienvenue02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string btnAccueil {
            get {
                return ResourceManager.GetString("btnAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string btnConnect {
            get {
                return ResourceManager.GetString("btnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string btnContact {
            get {
                return ResourceManager.GetString("btnContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string btnDeconnect {
            get {
                return ResourceManager.GetString("btnDeconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nos biens .
        /// </summary>
        public static string btnLesBiens {
            get {
                return ResourceManager.GetString("btnLesBiens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon profile.
        /// </summary>
        public static string btnMonProfil {
            get {
                return ResourceManager.GetString("btnMonProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau Bien.
        /// </summary>
        public static string btnNvBien {
            get {
                return ResourceManager.GetString("btnNvBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;enregistrer.
        /// </summary>
        public static string btnNvMembre {
            get {
                return ResourceManager.GetString("btnNvMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chambre.
        /// </summary>
        public static string chambre {
            get {
                return ResourceManager.GetString("chambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à commentaire.
        /// </summary>
        public static string commentaire {
            get {
                return ResourceManager.GetString("commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à une question?.
        /// </summary>
        public static string Contact01 {
            get {
                return ResourceManager.GetString("Contact01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contactez nous au :.
        /// </summary>
        public static string Contact02 {
            get {
                return ResourceManager.GetString("Contact02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse :.
        /// </summary>
        public static string Contact03 {
            get {
                return ResourceManager.GetString("Contact03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contacter le propriétaire.
        /// </summary>
        public static string contacterLeProprio {
            get {
                return ResourceManager.GetString("contacterLeProprio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à coût administratif.
        /// </summary>
        public static string coutAdmin {
            get {
                return ResourceManager.GetString("coutAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à coût du séjout.
        /// </summary>
        public static string coutSejour {
            get {
                return ResourceManager.GetString("coutSejour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cout total du séjour.
        /// </summary>
        public static string coutTot {
            get {
                return ResourceManager.GetString("coutTot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cuisine.
        /// </summary>
        public static string cuisine {
            get {
                return ResourceManager.GetString("cuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cuisine équipée.
        /// </summary>
        public static string cuisineEq {
            get {
                return ResourceManager.GetString("cuisineEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;arrivée.
        /// </summary>
        public static string DateArrivees {
            get {
                return ResourceManager.GetString("DateArrivees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance.
        /// </summary>
        public static string dateDeNaissance {
            get {
                return ResourceManager.GetString("dateDeNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de retour.
        /// </summary>
        public static string DateRetour {
            get {
                return ResourceManager.GetString("DateRetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à derniers commentaires.
        /// </summary>
        public static string dernierComment {
            get {
                return ResourceManager.GetString("dernierComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à déscription.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à détail du bien.
        /// </summary>
        public static string detailDuBien {
            get {
                return ResourceManager.GetString("detailDuBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dressing.
        /// </summary>
        public static string dressing {
            get {
                return ResourceManager.GetString("dressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrez-vous ici.
        /// </summary>
        public static string enregistrezVsIci {
            get {
                return ResourceManager.GetString("enregistrezVsIci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string envoyer {
            get {
                return ResourceManager.GetString("envoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à équipement.
        /// </summary>
        public static string equipement {
            get {
                return ResourceManager.GetString("equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à adresse requise.
        /// </summary>
        public static string Error_adresseRequise {
            get {
                return ResourceManager.GetString("Error_adresseRequise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à date de naissance requise.
        /// </summary>
        public static string Error_DateNaissRequis {
            get {
                return ResourceManager.GetString("Error_DateNaissRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant requis.
        /// </summary>
        public static string Error_identifiantRequis {
            get {
                return ResourceManager.GetString("Error_identifiantRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mail requis.
        /// </summary>
        public static string Error_mailRequis {
            get {
                return ResourceManager.GetString("Error_mailRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mesage requis.
        /// </summary>
        public static string Error_MessageRequis {
            get {
                return ResourceManager.GetString("Error_MessageRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nom requis.
        /// </summary>
        public static string Error_nomRequis {
            get {
                return ResourceManager.GetString("Error_nomRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à numéro requis.
        /// </summary>
        public static string Error_NumeroRequis {
            get {
                return ResourceManager.GetString("Error_NumeroRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mot de passe requis.
        /// </summary>
        public static string Error_PasswordRequis {
            get {
                return ResourceManager.GetString("Error_PasswordRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pays requis.
        /// </summary>
        public static string Error_PaysRequis {
            get {
                return ResourceManager.GetString("Error_PaysRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à prénom requis.
        /// </summary>
        public static string Error_PrenomRequis {
            get {
                return ResourceManager.GetString("Error_PrenomRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rue requise.
        /// </summary>
        public static string Error_rueRequis {
            get {
                return ResourceManager.GetString("Error_rueRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sujet requis.
        /// </summary>
        public static string Error_SujetRequis {
            get {
                return ResourceManager.GetString("Error_SujetRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à num de téléphone requis.
        /// </summary>
        public static string Error_telephoneRequis {
            get {
                return ResourceManager.GetString("Error_telephoneRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ville requise.
        /// </summary>
        public static string Error_VilleRequis {
            get {
                return ResourceManager.GetString("Error_VilleRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Est propriétaire.
        /// </summary>
        public static string estProprio {
            get {
                return ResourceManager.GetString("estProprio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à identifiant du bien.
        /// </summary>
        public static string idBien {
            get {
                return ResourceManager.GetString("idBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à identifiez-vous svp.
        /// </summary>
        public static string identifiezVous {
            get {
                return ResourceManager.GetString("identifiezVous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant.
        /// </summary>
        public static string idMembre {
            get {
                return ResourceManager.GetString("idMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jacuzzi.
        /// </summary>
        public static string jacuzzi {
            get {
                return ResourceManager.GetString("jacuzzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jardin.
        /// </summary>
        public static string jardin {
            get {
                return ResourceManager.GetString("jardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à les pièces.
        /// </summary>
        public static string lesPieces {
            get {
                return ResourceManager.GetString("lesPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à libelle.
        /// </summary>
        public static string libelle {
            get {
                return ResourceManager.GetString("libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à louer.
        /// </summary>
        public static string louer {
            get {
                return ResourceManager.GetString("louer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à louer un bien.
        /// </summary>
        public static string louerUnBien {
            get {
                return ResourceManager.GetString("louerUnBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à machine à laver.
        /// </summary>
        public static string machineALaver {
            get {
                return ResourceManager.GetString("machineALaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mes biens.
        /// </summary>
        public static string mesBiens {
            get {
                return ResourceManager.GetString("mesBiens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mes locations.
        /// </summary>
        public static string mesLocations {
            get {
                return ResourceManager.GetString("mesLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mes messages.
        /// </summary>
        public static string mesMessages {
            get {
                return ResourceManager.GetString("mesMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à veuillez vous connecter pour pouvoir louer un bien svp.
        /// </summary>
        public static string Modal_sIdentifierPourLouer {
            get {
                return ResourceManager.GetString("Modal_sIdentifierPourLouer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à modifier.
        /// </summary>
        public static string modifier {
            get {
                return ResourceManager.GetString("modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nbre de personne max.
        /// </summary>
        public static string nbPersMax {
            get {
                return ResourceManager.GetString("nbPersMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nombre de personne(s).
        /// </summary>
        public static string nbreDePers {
            get {
                return ResourceManager.GetString("nbreDePers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nombre de nuit.
        /// </summary>
        public static string nombreDeNuits {
            get {
                return ResourceManager.GetString("nombreDeNuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à note moyenne.
        /// </summary>
        public static string noteMoyenne {
            get {
                return ResourceManager.GetString("noteMoyenne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à numéro.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir.
        /// </summary>
        public static string parcourir {
            get {
                return ResourceManager.GetString("parcourir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parking.
        /// </summary>
        public static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mot de passe.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à confirmer.
        /// </summary>
        public static string password2 {
            get {
                return ResourceManager.GetString("password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à min 6 caractères.
        /// </summary>
        public static string PasswordProp {
            get {
                return ResourceManager.GetString("PasswordProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pays.
        /// </summary>
        public static string pays {
            get {
                return ResourceManager.GetString("pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays ou ville.
        /// </summary>
        public static string paysOuVille {
            get {
                return ResourceManager.GetString("paysOuVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pingpong.
        /// </summary>
        public static string pingpong {
            get {
                return ResourceManager.GetString("pingpong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à piscine.
        /// </summary>
        public static string piscine {
            get {
                return ResourceManager.GetString("piscine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string prenom {
            get {
                return ResourceManager.GetString("prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rue.
        /// </summary>
        public static string rue {
            get {
                return ResourceManager.GetString("rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à salon.
        /// </summary>
        public static string salon {
            get {
                return ResourceManager.GetString("salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à salle à manger.
        /// </summary>
        public static string sam {
            get {
                return ResourceManager.GetString("sam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sauna.
        /// </summary>
        public static string sauna {
            get {
                return ResourceManager.GetString("sauna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à salle de bain.
        /// </summary>
        public static string sdb {
            get {
                return ResourceManager.GetString("sdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        public static string sujet {
            get {
                return ResourceManager.GetString("sujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tarif pour le nettoyage.
        /// </summary>
        public static string tarifNettoyage {
            get {
                return ResourceManager.GetString("tarifNettoyage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tarif par nuit.
        /// </summary>
        public static string tarifNuit {
            get {
                return ResourceManager.GetString("tarifNuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à télédistribution.
        /// </summary>
        public static string teledistrib {
            get {
                return ResourceManager.GetString("teledistrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tennis.
        /// </summary>
        public static string tennis {
            get {
                return ResourceManager.GetString("tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur DREAMHOLIDAY.
        /// </summary>
        public static string TitreHome {
            get {
                return ResourceManager.GetString("TitreHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à toilette.
        /// </summary>
        public static string toilette {
            get {
                return ResourceManager.GetString("toilette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à transat.
        /// </summary>
        public static string transat {
            get {
                return ResourceManager.GetString("transat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouvez vos vacances de rêve.
        /// </summary>
        public static string trouvezVacDeReve {
            get {
                return ResourceManager.GetString("trouvezVacDeReve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à télévision.
        /// </summary>
        public static string tv {
            get {
                return ResourceManager.GetString("tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à veranda.
        /// </summary>
        public static string veranda {
            get {
                return ResourceManager.GetString("veranda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ville.
        /// </summary>
        public static string ville {
            get {
                return ResourceManager.GetString("ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vous n&apos;avez pas.
        /// </summary>
        public static string vousAvezPasDeBien1 {
            get {
                return ResourceManager.GetString("vousAvezPasDeBien1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à encore de bien.
        /// </summary>
        public static string vousAvezPasDeBien2 {
            get {
                return ResourceManager.GetString("vousAvezPasDeBien2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vous n&apos;avez pas.
        /// </summary>
        public static string vousAvezPasDeLoc1 {
            get {
                return ResourceManager.GetString("vousAvezPasDeLoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à encore loué de bien.
        /// </summary>
        public static string vousAvezPasDeLoc2 {
            get {
                return ResourceManager.GetString("vousAvezPasDeLoc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vous n&apos;avez pas.
        /// </summary>
        public static string vousAvezPasDeMsg1 {
            get {
                return ResourceManager.GetString("vousAvezPasDeMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à encore de message.
        /// </summary>
        public static string vousAvezPasDeMsg2 {
            get {
                return ResourceManager.GetString("vousAvezPasDeMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wifi.
        /// </summary>
        public static string wifi {
            get {
                return ResourceManager.GetString("wifi", resourceCulture);
            }
        }
    }
}
